-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.auditorias_compatibilidade (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL,
  persona_id uuid NOT NULL,
  workflow_reference character varying NOT NULL,
  meta_global_id uuid,
  meta_persona_id uuid,
  compatibilidade_score integer NOT NULL CHECK (compatibilidade_score >= 0 AND compatibilidade_score <= 100),
  compatibilidade_nivel character varying NOT NULL DEFAULT 'medio'::character varying CHECK (compatibilidade_nivel::text = ANY (ARRAY['baixo'::character varying, 'medio'::character varying, 'alto'::character varying, 'excelente'::character varying]::text[])),
  analise_detalhada jsonb DEFAULT '{}'::jsonb,
  observacoes text,
  acoes_sugeridas ARRAY,
  status_auditoria character varying NOT NULL DEFAULT 'pendente'::character varying CHECK (status_auditoria::text = ANY (ARRAY['pendente'::character varying, 'em_analise'::character varying, 'aprovado'::character varying, 'reprovado'::character varying, 'requer_ajuste'::character varying]::text[])),
  auditado_por character varying,
  auditado_em timestamp with time zone,
  proxima_auditoria date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT auditorias_compatibilidade_pkey PRIMARY KEY (id),
  CONSTRAINT auditorias_compatibilidade_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.empresas(id),
  CONSTRAINT auditorias_compatibilidade_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.personas(id),
  CONSTRAINT auditorias_compatibilidade_meta_global_id_fkey FOREIGN KEY (meta_global_id) REFERENCES public.metas_globais(id),
  CONSTRAINT auditorias_compatibilidade_meta_persona_id_fkey FOREIGN KEY (meta_persona_id) REFERENCES public.metas_personas(id)
);
CREATE TABLE public.avatares_personas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  persona_id uuid NOT NULL,
  avatar_url character varying NOT NULL,
  avatar_thumbnail_url character varying,
  prompt_usado text NOT NULL,
  estilo character varying NOT NULL DEFAULT 'corporate'::character varying CHECK (estilo::text = ANY (ARRAY['corporate'::character varying, 'casual'::character varying, 'creative'::character varying, 'formal'::character varying]::text[])),
  background_tipo character varying NOT NULL DEFAULT 'office'::character varying CHECK (background_tipo::text = ANY (ARRAY['office'::character varying, 'home_office'::character varying, 'neutral'::character varying, 'custom'::character varying]::text[])),
  servico_usado character varying NOT NULL DEFAULT 'nano_banana'::character varying CHECK (servico_usado::text = ANY (ARRAY['nano_banana'::character varying, 'dall_e'::character varying, 'midjourney'::character varying, 'custom'::character varying]::text[])),
  versao integer NOT NULL DEFAULT 1,
  ativo boolean NOT NULL DEFAULT true,
  metadados jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT avatares_personas_pkey PRIMARY KEY (id),
  CONSTRAINT avatares_personas_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.personas(id)
);
CREATE TABLE public.competencias (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  persona_id uuid NOT NULL,
  tipo character varying NOT NULL CHECK (tipo::text = ANY (ARRAY['principal'::character varying, 'tecnica'::character varying, 'soft_skill'::character varying]::text[])),
  nome character varying NOT NULL,
  descricao text,
  nivel character varying DEFAULT 'avancado'::character varying CHECK (nivel::text = ANY (ARRAY['basico'::character varying, 'intermediario'::character varying, 'avancado'::character varying, 'expert'::character varying]::text[])),
  categoria character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT competencias_pkey PRIMARY KEY (id),
  CONSTRAINT competencias_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.personas(id)
);
CREATE TABLE public.empresas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  codigo character varying NOT NULL UNIQUE,
  nome character varying NOT NULL,
  descricao text NOT NULL,
  pais character varying NOT NULL DEFAULT 'BR'::character varying,
  idiomas ARRAY NOT NULL DEFAULT ARRAY['pt'::text],
  total_personas integer NOT NULL DEFAULT 20,
  status character varying NOT NULL DEFAULT 'ativa'::character varying CHECK (status::text = ANY (ARRAY['ativa'::character varying, 'inativa'::character varying, 'processando'::character varying]::text[])),
  scripts_status jsonb NOT NULL DEFAULT '{"rag": false, "fluxos": false, "workflows": false, "biografias": false, "tech_specs": false, "competencias": false}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  ceo_gender character varying DEFAULT 'feminino'::character varying,
  executives_male integer DEFAULT 0,
  executives_female integer DEFAULT 0,
  assistants_male integer DEFAULT 0,
  assistants_female integer DEFAULT 0,
  specialists_male integer DEFAULT 0,
  specialists_female integer DEFAULT 0,
  industry character varying DEFAULT 'tecnologia'::character varying,
  nationalities jsonb DEFAULT '[]'::jsonb,
  dominio character varying,
  industria character varying NOT NULL DEFAULT 'tecnologia'::character varying,
  CONSTRAINT empresas_pkey PRIMARY KEY (id)
);
CREATE TABLE public.metas_globais (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL,
  titulo character varying NOT NULL,
  descricao text NOT NULL,
  prazo date NOT NULL,
  prioridade character varying NOT NULL DEFAULT 'media'::character varying CHECK (prioridade::text = ANY (ARRAY['baixa'::character varying, 'media'::character varying, 'alta'::character varying, 'critica'::character varying]::text[])),
  categoria character varying NOT NULL DEFAULT 'crescimento'::character varying CHECK (categoria::text = ANY (ARRAY['crescimento'::character varying, 'operacional'::character varying, 'financeira'::character varying, 'inovacao'::character varying, 'sustentabilidade'::character varying]::text[])),
  progresso integer DEFAULT 0 CHECK (progresso >= 0 AND progresso <= 100),
  status character varying NOT NULL DEFAULT 'ativa'::character varying CHECK (status::text = ANY (ARRAY['ativa'::character varying, 'pausada'::character varying, 'concluida'::character varying, 'cancelada'::character varying]::text[])),
  responsavel_principal character varying,
  indicadores_sucesso ARRAY,
  budget_estimado numeric,
  roi_esperado numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT metas_globais_pkey PRIMARY KEY (id),
  CONSTRAINT metas_globais_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.empresas(id)
);
CREATE TABLE public.metas_personas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  meta_global_id uuid NOT NULL,
  persona_id uuid NOT NULL,
  titulo character varying NOT NULL,
  descricao text NOT NULL,
  tipo_persona character varying NOT NULL CHECK (tipo_persona::text = ANY (ARRAY['executivo'::character varying, 'especialista'::character varying, 'assistente'::character varying]::text[])),
  prazo date NOT NULL,
  progresso integer DEFAULT 0 CHECK (progresso >= 0 AND progresso <= 100),
  alinhamento_score integer DEFAULT 0 CHECK (alinhamento_score >= 0 AND alinhamento_score <= 100),
  status character varying NOT NULL DEFAULT 'ativa'::character varying CHECK (status::text = ANY (ARRAY['ativa'::character varying, 'pausada'::character varying, 'concluida'::character varying, 'cancelada'::character varying]::text[])),
  dependencias ARRAY,
  recursos_necessarios ARRAY,
  milestones jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT metas_personas_pkey PRIMARY KEY (id),
  CONSTRAINT metas_personas_meta_global_id_fkey FOREIGN KEY (meta_global_id) REFERENCES public.metas_globais(id),
  CONSTRAINT metas_personas_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.personas(id)
);
CREATE TABLE public.persona_collection_access (
  persona_id uuid NOT NULL,
  collection_id uuid NOT NULL,
  role text NOT NULL DEFAULT 'reader'::text CHECK (role = ANY (ARRAY['reader'::text, 'editor'::text, 'owner'::text])),
  granted_at timestamp with time zone DEFAULT now(),
  granted_by uuid,
  CONSTRAINT persona_collection_access_pkey PRIMARY KEY (persona_id, collection_id),
  CONSTRAINT persona_collection_access_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.personas(id),
  CONSTRAINT persona_collection_access_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES public.rag_collections(id)
);
CREATE TABLE public.personas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  persona_code character varying NOT NULL UNIQUE,
  full_name character varying NOT NULL,
  role character varying NOT NULL,
  specialty character varying,
  department character varying,
  email character varying NOT NULL UNIQUE,
  whatsapp character varying NOT NULL,
  empresa_id uuid NOT NULL,
  biografia_completa text,
  personalidade jsonb DEFAULT '{}'::jsonb,
  experiencia_anos integer DEFAULT 0,
  ia_config jsonb DEFAULT '{}'::jsonb,
  temperatura_ia numeric DEFAULT 0.7,
  max_tokens integer DEFAULT 2000,
  system_prompt text,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'archived'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_sync timestamp with time zone DEFAULT now(),
  CONSTRAINT personas_pkey PRIMARY KEY (id),
  CONSTRAINT personas_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.empresas(id)
);
CREATE TABLE public.personas_biografias (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  persona_id uuid NOT NULL UNIQUE,
  biografia_completa text NOT NULL,
  historia_profissional text,
  motivacoes jsonb DEFAULT '{}'::jsonb,
  desafios jsonb DEFAULT '{}'::jsonb,
  objetivos_pessoais ARRAY,
  soft_skills jsonb DEFAULT '{}'::jsonb,
  hard_skills jsonb DEFAULT '{}'::jsonb,
  educacao jsonb DEFAULT '{}'::jsonb,
  certificacoes ARRAY,
  idiomas_fluencia jsonb DEFAULT '{}'::jsonb,
  experiencia_internacional jsonb DEFAULT '{}'::jsonb,
  redes_sociais jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT personas_biografias_pkey PRIMARY KEY (id),
  CONSTRAINT personas_biografias_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.personas(id)
);
CREATE TABLE public.personas_tech_specs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  persona_id uuid NOT NULL UNIQUE,
  ai_model character varying NOT NULL DEFAULT 'gpt-4-turbo-preview'::character varying,
  max_tokens integer NOT NULL DEFAULT 2000 CHECK (max_tokens > 0 AND max_tokens <= 8000),
  temperature numeric NOT NULL DEFAULT 0.7 CHECK (temperature >= 0::numeric AND temperature <= 2::numeric),
  response_format character varying NOT NULL DEFAULT 'structured'::character varying CHECK (response_format::text = ANY (ARRAY['structured'::character varying, 'creative'::character varying, 'analytical'::character varying, 'conversational'::character varying]::text[])),
  priority_level character varying NOT NULL DEFAULT 'medium'::character varying CHECK (priority_level::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'critical'::character varying]::text[])),
  decision_authority character varying NOT NULL DEFAULT 'operational'::character varying CHECK (decision_authority::text = ANY (ARRAY['none'::character varying, 'operational'::character varying, 'tactical'::character varying, 'strategic'::character varying, 'full'::character varying]::text[])),
  access_scope character varying NOT NULL DEFAULT 'department'::character varying,
  tools_habilitadas jsonb DEFAULT '[]'::jsonb,
  integrações_sistemas jsonb DEFAULT '[]'::jsonb,
  limitações jsonb DEFAULT '{}'::jsonb,
  configuração_avançada jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT personas_tech_specs_pkey PRIMARY KEY (id),
  CONSTRAINT personas_tech_specs_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.personas(id)
);
CREATE TABLE public.rag_chunks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  document_id uuid NOT NULL,
  chunk_index integer NOT NULL,
  content text NOT NULL,
  content_length integer,
  tokens integer,
  metadata jsonb DEFAULT '{}'::jsonb,
  start_char integer,
  end_char integer,
  overlap_prev integer DEFAULT 0,
  overlap_next integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  embedding USER-DEFINED,
  CONSTRAINT rag_chunks_pkey PRIMARY KEY (id),
  CONSTRAINT rag_chunks_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.rag_documents(id)
);
CREATE TABLE public.rag_collections (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  visibility text NOT NULL DEFAULT 'public'::text CHECK (visibility = ANY (ARRAY['public'::text, 'internal'::text, 'restricted'::text])),
  tags ARRAY DEFAULT ARRAY[]::text[],
  metadata jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rag_collections_pkey PRIMARY KEY (id)
);
CREATE TABLE public.rag_config_empresa (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL UNIQUE,
  chunk_size integer DEFAULT 1000,
  chunk_overlap integer DEFAULT 200,
  embedding_model character varying DEFAULT 'text-embedding-ada-002'::character varying,
  similarity_threshold numeric DEFAULT 0.7,
  max_results integer DEFAULT 5,
  auto_sync boolean DEFAULT true,
  last_sync timestamp with time zone,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rag_config_empresa_pkey PRIMARY KEY (id)
);
CREATE TABLE public.rag_documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  collection_id uuid NOT NULL,
  external_id text NOT NULL,
  title text NOT NULL,
  content_raw text,
  content_length integer,
  language text NOT NULL DEFAULT 'en'::text,
  version text DEFAULT 'latest'::text,
  document_type text,
  source_url text,
  checksum text,
  metadata jsonb DEFAULT '{}'::jsonb,
  tags ARRAY DEFAULT ARRAY[]::text[],
  is_active boolean DEFAULT true,
  processed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  embedding USER-DEFINED,
  empresa_id uuid,
  source_type character varying DEFAULT 'manual'::character varying,
  persona_id uuid,
  CONSTRAINT rag_documents_pkey PRIMARY KEY (id),
  CONSTRAINT rag_documents_collection_id_fkey FOREIGN KEY (collection_id) REFERENCES public.rag_collections(id)
);
CREATE TABLE public.rag_eval_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  eval_set_id uuid NOT NULL,
  query text NOT NULL,
  expected_chunks ARRAY DEFAULT ARRAY[]::uuid[],
  expected_answer text,
  difficulty_level integer CHECK (difficulty_level >= 1 AND difficulty_level <= 5),
  tags ARRAY DEFAULT ARRAY[]::text[],
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rag_eval_items_pkey PRIMARY KEY (id),
  CONSTRAINT rag_eval_items_eval_set_id_fkey FOREIGN KEY (eval_set_id) REFERENCES public.rag_eval_sets(id)
);
CREATE TABLE public.rag_eval_sets (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  description text,
  persona_id uuid,
  collection_ids ARRAY DEFAULT ARRAY[]::uuid[],
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rag_eval_sets_pkey PRIMARY KEY (id)
);
CREATE TABLE public.rag_feedback (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  persona_id uuid,
  session_id text,
  query text NOT NULL,
  answer_quality integer CHECK (answer_quality >= 1 AND answer_quality <= 5),
  relevance_score numeric CHECK (relevance_score >= 0::numeric AND relevance_score <= 1::numeric),
  response_time_ms integer,
  reasons text,
  top_citations jsonb DEFAULT '[]'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rag_feedback_pkey PRIMARY KEY (id)
);
CREATE TABLE public.rag_ingestion_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL,
  job_type character varying NOT NULL,
  status character varying DEFAULT 'pending'::character varying,
  total_items integer DEFAULT 0,
  processed_items integer DEFAULT 0,
  success_items integer DEFAULT 0,
  failed_items integer DEFAULT 0,
  error_details jsonb DEFAULT '[]'::jsonb,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rag_ingestion_jobs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.rag_ingestion_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  document_id uuid,
  status text NOT NULL CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text, 'retrying'::text])),
  operation text NOT NULL,
  chunks_created integer DEFAULT 0,
  chunks_updated integer DEFAULT 0,
  processing_time_ms integer,
  error_message text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT rag_ingestion_logs_pkey PRIMARY KEY (id),
  CONSTRAINT rag_ingestion_logs_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.rag_documents(id)
);
CREATE TABLE public.rag_knowledge (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  persona_id uuid NOT NULL,
  tipo character varying NOT NULL CHECK (tipo::text = ANY (ARRAY['politica'::character varying, 'procedimento'::character varying, 'documento'::character varying, 'faq'::character varying]::text[])),
  titulo character varying NOT NULL,
  conteudo text NOT NULL,
  chunk_size integer DEFAULT 800,
  tokens_count integer,
  categoria character varying,
  tags jsonb DEFAULT '[]'::jsonb,
  relevancia numeric DEFAULT 1.0,
  ativo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rag_knowledge_pkey PRIMARY KEY (id),
  CONSTRAINT rag_knowledge_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.personas(id)
);
CREATE TABLE public.sync_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  empresa_id uuid NOT NULL,
  tipo_sync character varying NOT NULL,
  status character varying NOT NULL CHECK (status::text = ANY (ARRAY['success'::character varying, 'error'::character varying, 'partial'::character varying]::text[])),
  registros_processados integer DEFAULT 0,
  registros_sucesso integer DEFAULT 0,
  registros_erro integer DEFAULT 0,
  detalhes jsonb DEFAULT '{}'::jsonb,
  error_log text,
  started_at timestamp with time zone DEFAULT now(),
  finished_at timestamp with time zone,
  duration_seconds integer,
  CONSTRAINT sync_logs_pkey PRIMARY KEY (id),
  CONSTRAINT sync_logs_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.empresas(id)
);
CREATE TABLE public.system_configurations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key character varying NOT NULL UNIQUE,
  value text NOT NULL,
  category character varying NOT NULL CHECK (category::text = ANY (ARRAY['api'::character varying, 'system'::character varying, 'ui'::character varying, 'sync'::character varying]::text[])),
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT system_configurations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.workflows (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  persona_id uuid NOT NULL,
  nome character varying NOT NULL,
  descricao text,
  tipo character varying NOT NULL CHECK (tipo::text = ANY (ARRAY['tarefa'::character varying, 'fluxo'::character varying, 'responsabilidade'::character varying]::text[])),
  prioridade character varying DEFAULT 'media'::character varying CHECK (prioridade::text = ANY (ARRAY['baixa'::character varying, 'media'::character varying, 'alta'::character varying, 'critica'::character varying]::text[])),
  config jsonb DEFAULT '{}'::jsonb,
  triggers jsonb DEFAULT '[]'::jsonb,
  actions jsonb DEFAULT '[]'::jsonb,
  ativo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workflows_pkey PRIMARY KEY (id),
  CONSTRAINT workflows_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES public.personas(id)
);